env:
  global:
    - CC_TEST_REPORTER_ID=fea3ceb48785ba8d314ed54db1e2a8967f7095161e472b6f6c545cce914b3060

language: go

go:
  - "1.10.x"

script:
  - go test ./... -test.bench=".*" -test.benchtime 100ms -v -coverprofile c.out
  - gofmt -s -l .

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT